---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: scripts/docker-auth.sh
      - run: scripts/docker-build-image.sh
      - run: scripts/docker-test-image.sh
      - run: scripts/docker-push-image.sh
      - persist_to_workspace:
          root: .
          paths:
            - .dockerrepo
            - .dockertag
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Docker Hub
