---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: scripts/docker-auth.sh
      - run: scripts/docker-build-image.sh
      - run: scripts/docker-test-image.sh
      - run: scripts/docker-push-image.sh
      - persist_to_workspace:
          root: .
          paths:
            - .dockerrepo
            - .dockertag
  deploy-prod:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "f4:52:63:45:e1:f9:17:89:61:f6:ba:0f:e7:65:a7:48"
      - run: scripts/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Docker Hub
